name: Deploy

on:
  push:
    branches: "main"


concurrency:
  group: "surge"
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run application
        run: docker compose up -d frontend

      - name: Run cypress test
        run: docker compose run cypress

  deploy:
    runs-on: ubuntu-latest
    needs: e2e
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Tests coverage
        run: npm run coverage

      - name: Build
        run: npm run build

      - name: Deploy to surge
        run: |
          npm install -g surge
          surge ./dist --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - name: Upload error report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: error-report
          path: ./coverage.json
